### ISSUE TITLE
Translations/Text Changes

### ISSUE THREAD

**Issue by ghost** [RiiConnect24/acw-patcher#1]
Changes are needed for:
- [ ] Japanese
- [ ] US English
- [ ] US French
- [ ] US Spanish
- [x] EU English
- [ ] EU German
- [ ] EU French
- [ ] EU Spanish
- [ ] EU Dutch
- [ ] EU Italian
- [ ] Korean
- [ ] Chinese

See https://github.com/PokeAcer549/acw-patcher/blob/master/Translation.md

**Comment by ghost** [comment]
This shouldn't be closed; it's still needing to be done.

**Comment by larsenv** [comment]
The translations are already done by me. That's why it was closed.
