### ISSUE TITLE
Reporting a problem in Town Hall messes up villager's names

### ISSUE THREAD

**Issue by adueppen** [RiiConnect24/acw-patcher#3]
I went to Pelly and reported a villager for being rude. Everything seemed to be normal until she asked about having a word with them, at which point there were a number of invalid characters. The yes/no dialog choice also did not show up. It's possible this issue could be caused by something else, but I didn't notice it before patching the game. Screenshot: ![ruu_0003](https://user-images.githubusercontent.com/6982070/26939677-ae715c5c-4c3d-11e7-8e7d-87bd34661fae.JPG)

**Comment by larsenv** [comment]
Hmm, not sure what could be causing the problem... I'd have to look at it but it'd be tedious to fix I bet, ugh.

**Comment by adueppen** [comment]
I'm running the game off a FAT32 flash drive through USB Loader GX. It's also converted to WBFS.

**Comment by larsenv** [comment]
Did the game freeze or something? Were you able to exit out of the dialog?

**Comment by adueppen** [comment]
The game didn't freeze or anything, the only thing that seems to be wrong is the text and the lack of the yes/no thing. It just closed the textbox instead of showing anything. I'd imagine the invalid characters are supposed to be the yes/no.

**Comment by larsenv** [comment]
I think I found where the issue was occurring, I'll see what I can do about fixing it.

For now I updated the release.

**Comment by KcrPL** [comment]
Or maybe it's just problem with your save/game. Try downloading this game again and try to patch it again using the newest version of patcher.
