### ISSUE TITLE
 File check has failed

### ISSUE THREAD

**Issue by Trimbell** [RiiConnect24/acw-patcher#5]
Hi there, I'm trying to patch animal crossing but when I open the patcher, I get this on my screen:

```
Animal Crossing Patcher for Wiimmfi/RiiConnect24 - (C)KcrPL, (C)Larsenv, (C)PokeAcer549 and (C)Shutterbug2000
v2.1.1. (Compiled on 2017/10/20 at 21:52)
------------------------------------------------------------------------------------------------------------------------------ [*] ERROR.

It seems that error has occurred.

File check has failed. Please redownload this package or unpack it.

Cannot continue, press anything to exit patcher.
```

Any idea what I'm doing wrong? I do have my Animal Crossing WBFS file in the same folder as the patcher, so I'm not sure why it won't work.
I am using this on Windows 10, if that helps at all.

**Comment by larsenv** [comment]
Did you download the acw-patcher.zip from Releases?

**Comment by Trimbell** [comment]
Yes, I downloaded the zip file and extracted the contents of the "Windows" folder.

**Comment by larsenv** [comment]
Does the "BMG" folder exist in the directory above the Windows folder?

**Comment by Trimbell** [comment]
No, I didn't realize I had to extract that as well. I just did and the injector worked perfectly. Thanks for the help.

**Comment by larsenv** [comment]
No problem. I'll close the commit, if you remain to have problems please comment.

**Comment by KcrPL** [comment]
Let's be real, *this patcher sucks*.

I pretty much abandoned it and now it's time to rewrite it.
Also when I'll add updating to the patcher, problems like these will be solved.
